server:
  port: 9090   # Gateway runs on 9090
logging:
  level:
    ROOT: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: wallet-service
          uri: http://localhost:8081
          predicates:
            - Path=/wallet-service/**

        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/user-service/**

        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/transaction-service/**
